# Generated by Django 5.0.8 on 2025-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('chat', 'Chat'), ('announce', 'Announce')], default='chat', max_length=10)),
                ('content', models.CharField(max_length=128)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('room_picture', models.ImageField(blank=True, null=True, upload_to='room_pictures/')),
            ],
        ),
    ]
