# Generated by Django 5.0.8 on 2025-08-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flappy', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flappygame',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flappy_as_player1', to='user.user'),
        ),
        migrations.AddField(
            model_name='flappygame',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flappy_as_player2', to='user.user'),
        ),
        migrations.AddField(
            model_name='flappygame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flappy_won', to='user.user'),
        ),
    ]
